### Get posts 
GET http://localhost:3001/

### Login with valid credentials 
POST http://localhost:3001/user/login 
Content-Type: application/json

{
"username":"admin", 
"password":"12345678"
}

### Login with invalid credentials 
POST http://localhost:3001/user/login 
Content-Type: application/json

{
"username":"admin", 
"password":"wrongpassword"
}

### test passwordreset email exsits 
POST http://localhost:3001/user/reset
Content-Type: application/json

{
"email":"admin@123456",
"newPassword":"newpassword"
}

### test passwordreset email dosent exsits 
POST http://localhost:3001/user/reset
Content-Type: application/json

{
"email":"admin@456",
"newPassword":"wrongpassword"
}

# 6.Apr Modification:
### Registration 
POST http://localhost:3001/user/signup
Content-Type: application/json

{
"username":"test16",
"email":"test16@gmail.com",
"password":"password"
}

# 7.Apr Modification:
### test email exsits
POST http://localhost:3001/user/check-email
Content-Type: application/json

{
"email":"test18@gmail.com"
}

### test email doesn't exsits 
POST http://localhost:3001/user/check-email
Content-Type: application/json

{
"email":"admin@456"
}

### test username exsits
POST http://localhost:3001/user/check-username
Content-Type: application/json

{
"username":"test18"
}

### test username doesn't exsits 
POST http://localhost:3001/user/check-username
Content-Type: application/json

{
"username":"admin@456"
}

### test password has been changed
POST http://localhost:3001/user/reset-password
Content-Type: application/json

{
"email":"test@gmail.com",
"newPassword":"12345678"
}

# 9.Apr modification:
### test add a new post
POST http://localhost:3001/post/create
Content-Type: application/json

{
    "title": "this is a new post",
    "content": "this is a new content",
    "username": "admin"
}





